
spring:
  first-datasource:
    url: jdbc:mysql://localhost:3306/information_schema?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  second-datasource:
    url: jdbc:mysql://localhost:3306/recruiting?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver